#POST https://ycsqswlldpzuspadjerc.supabase.co/functions/v1/signup
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6ImIybmtyTUZOYzg0TDl5cVMiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3ljc3Fzd2xsZHB6dXNwYWRqZXJjLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiIwYTRjNDdlZS1lYjg4LTQ3N2QtOTgzNy0zZDc1NWQ5ZmQ4ZGYiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzUyMzk4NzYyLCJpYXQiOjE3NTIzOTUxNjIsImVtYWlsIjoidGVzdDEyM0BnbWFpbC5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsIjoidGVzdDEyM0BnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwicGhvbmVfdmVyaWZpZWQiOmZhbHNlLCJzdWIiOiIwYTRjNDdlZS1lYjg4LTQ3N2QtOTgzNy0zZDc1NWQ5ZmQ4ZGYifSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTc1MjM5NTE2Mn1dLCJzZXNzaW9uX2lkIjoiZGYzNWM4ZGItMjQ0Ni00M2ZkLTgzMTctZDA5YmYyZGMyM2E4IiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.pTdc0ruI5_XoyPnlT4mDKi3cV2dvQp6IdXcJsjQpf8I
#Content-Type: application/json
#Origin: http://localhost:3000
#
#{
#  "full_name": "Test Student",
#  "registration_number": "CS2025-001",
#  "department": "Computer Science",
#  "year": 2,
#  "email": "test123@gmail.com",
#  "role": "student"
#}
#GET https://ycsqswlldpzuspadjerc.supabase.co/rest/v1/users?select=role&id=eq.d63c9f1f-bd30-4ea6-a9f8-24517451f459
#Authorization: Bearer  eyJhbGciOiJIUzI1NiIsImtpZCI6ImIybmtyTUZOYzg0TDl5cVMiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3ljc3Fzd2xsZHB6dXNwYWRqZXJjLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiJkNjNjOWYxZi1iZDMwLTRlYTYtYTlmOC0yNDUxNzQ1MWY0NTkiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzUyNDI4Njc4LCJpYXQiOjE3NTI0MjUwNzgsImVtYWlsIjoidGVzdDEyM0BnbWFpbC5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsIjoidGVzdDEyM0BnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwicGhvbmVfdmVyaWZpZWQiOmZhbHNlLCJzdWIiOiJkNjNjOWYxZi1iZDMwLTRlYTYtYTlmOC0yNDUxNzQ1MWY0NTkifSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTc1MjQyNTA3OH1dLCJzZXNzaW9uX2lkIjoiYTg2YWE5Y2QtOTMyNC00MmZlLWFiY2QtZGE4ZTczN2NkODdlIiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.W2c9kPCXd6r9N9TiChGPRQdbaiYSdBmTQi5EqF-YoLo
#apikey:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inljc3Fzd2xsZHB6dXNwYWRqZXJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMzc2MjIsImV4cCI6MjA2NzkxMzYyMn0.4_8nNcRL5pM8UhEBuob8Wy6ah5uDG8XXkLojhgfC04I
#Accept: application/json